services:
  nest:
    container_name: nest
    build: ./nest-app
    restart: always
    environment:
      - BACK_PORT=${BACK_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - ${BACK_PORT}:${BACK_PORT} #temporary
    volumes:
      - nest_data:/app
      - files_to_compile:/volumes/files_to_compile
      - apk_files:/volumes/apk_files
    networks:
      - androAINetwork
    depends_on:
    - react

  react:
    container_name: react
    build: ./front 
    restart: always
    depends_on:
      - rasa
    environment:
      - FRONT_PORT=${FRONT_PORT}
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - react_data:/app
    networks:
      - androAINetwork

  android-builder:
    container_name: android-builder
    build: ./android-builder
    depends_on:
      - nest
    ports:
      - ${ANDROID_SERVER_PORT}:${ANDROID_SERVER_PORT} #temporary
    environment:
      - ANDROID_SERVER_PORT=${ANDROID_SERVER_PORT}
      - ANDROID_HOME=${ANDROID_HOME}
      - JAVA_HOME=${JAVA_HOME}
    volumes:
      - source_codes:/volumes/source_codes
      - files_to_compile:/volumes/files_to_compile
      - apk_files:/volumes/apk_files
    networks:
      - androAINetwork

  flask:
    container_name: flask-front
    build:
      context: ./Server
      dockerfile: Dockerfile
      args:
        FLASK_PORT: ${FLASK_PORT}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - FLASK_PORT=${FLASK_PORT}
      - NODE_ENV=development #for debugging
    depends_on:
      - rasa
    networks:
      - androAINetwork

  rasa:
    container_name: rasa
    image: rasa/rasa:latest
    ports:
      - "${RASA_PORT}:${RASA_PORT}"
    command:
      - run
      - --enable-api
      - --cors
      - '*'
      - --port
      - "${RASA_PORT}"
      - --endpoints
      - /app/endpoints.yml
    volumes:
      - ./assistant/models:/app/models
      - ./assistant/endpoints.yml:/app/endpoints.yml
    networks:
      - androAINetwork
    depends_on:
      - rasa_action_server

  rasa_action_server:
    container_name: rasa-actions
    build:
      context: ./assistant
      dockerfile: Dockerfile
    volumes:
      - ./assistant/actions:/app/actions
      - ./assistant/endpoints.yml:/app/endpoints.yml
    ports:
      - "${ACTION_SERVER_PORT}:${ACTION_SERVER_PORT}"
    networks:
      - androAINetwork
    command: ["start", "--actions", "actions"]

networks:
  androAINetwork:
    driver: bridge

volumes:
  files_to_compile:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/files_to_compile
      o: bind
  apk_files:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/apk_files
      o: bind
  source_codes:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/source_codes
      o: bind
  nest_data:
    driver: local
    driver_opts:
      type: none
      device: ./nest-app
      o: bind
  react_data:
    driver: local
    driver_opts:
      type: none
      device: ./front
      o: bind

