version: '3.8'

services:

  flask-server:
  
    build:
      context: ./Server
      dockerfile: Dockerfile
      
    ports:
      - "5000:5000"
      
    environment:
      ANDROID_HOME: "/sdk"
      JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
      
    volumes:
      - ./MyAndroidApp:/app/android


  android-builder:
  
    image: gradle:8.0-jdk17
    
    container_name: android-builder
    
    environment:
      ANDROID_HOME: "/sdk"
      JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
      
    volumes:
      - ./MyAndroidApp:/app
      
    working_dir: /app
    
    command: gradle build
